language: ruby
os:
  - linux
services: 
  - docker

before_install:
  - gem install bundler --pre
  - docker build -t justicea83/docker-react -f Dockerfile.dev .

script:
  - docker run justicea83/docker-react npm run test -- --coverage